require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CategoryParticipantsController do

  # This should return the minimal set of attributes required to create a valid
  # CategoryParticipant. As you add validations to CategoryParticipant, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CategoryParticipantsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all category_participants as @category_participants" do
      category_participant = CategoryParticipant.create! valid_attributes
      get :index, {}, valid_session
      assigns(:category_participants).should eq([category_participant])
    end
  end

  describe "GET show" do
    it "assigns the requested category_participant as @category_participant" do
      category_participant = CategoryParticipant.create! valid_attributes
      get :show, {:id => category_participant.to_param}, valid_session
      assigns(:category_participant).should eq(category_participant)
    end
  end

  describe "GET new" do
    it "assigns a new category_participant as @category_participant" do
      get :new, {}, valid_session
      assigns(:category_participant).should be_a_new(CategoryParticipant)
    end
  end

  describe "GET edit" do
    it "assigns the requested category_participant as @category_participant" do
      category_participant = CategoryParticipant.create! valid_attributes
      get :edit, {:id => category_participant.to_param}, valid_session
      assigns(:category_participant).should eq(category_participant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CategoryParticipant" do
        expect {
          post :create, {:category_participant => valid_attributes}, valid_session
        }.to change(CategoryParticipant, :count).by(1)
      end

      it "assigns a newly created category_participant as @category_participant" do
        post :create, {:category_participant => valid_attributes}, valid_session
        assigns(:category_participant).should be_a(CategoryParticipant)
        assigns(:category_participant).should be_persisted
      end

      it "redirects to the created category_participant" do
        post :create, {:category_participant => valid_attributes}, valid_session
        response.should redirect_to(CategoryParticipant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved category_participant as @category_participant" do
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryParticipant.any_instance.stub(:save).and_return(false)
        post :create, {:category_participant => {}}, valid_session
        assigns(:category_participant).should be_a_new(CategoryParticipant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryParticipant.any_instance.stub(:save).and_return(false)
        post :create, {:category_participant => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested category_participant" do
        category_participant = CategoryParticipant.create! valid_attributes
        # Assuming there are no other category_participants in the database, this
        # specifies that the CategoryParticipant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CategoryParticipant.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => category_participant.to_param, :category_participant => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested category_participant as @category_participant" do
        category_participant = CategoryParticipant.create! valid_attributes
        put :update, {:id => category_participant.to_param, :category_participant => valid_attributes}, valid_session
        assigns(:category_participant).should eq(category_participant)
      end

      it "redirects to the category_participant" do
        category_participant = CategoryParticipant.create! valid_attributes
        put :update, {:id => category_participant.to_param, :category_participant => valid_attributes}, valid_session
        response.should redirect_to(category_participant)
      end
    end

    describe "with invalid params" do
      it "assigns the category_participant as @category_participant" do
        category_participant = CategoryParticipant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryParticipant.any_instance.stub(:save).and_return(false)
        put :update, {:id => category_participant.to_param, :category_participant => {}}, valid_session
        assigns(:category_participant).should eq(category_participant)
      end

      it "re-renders the 'edit' template" do
        category_participant = CategoryParticipant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryParticipant.any_instance.stub(:save).and_return(false)
        put :update, {:id => category_participant.to_param, :category_participant => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested category_participant" do
      category_participant = CategoryParticipant.create! valid_attributes
      expect {
        delete :destroy, {:id => category_participant.to_param}, valid_session
      }.to change(CategoryParticipant, :count).by(-1)
    end

    it "redirects to the category_participants list" do
      category_participant = CategoryParticipant.create! valid_attributes
      delete :destroy, {:id => category_participant.to_param}, valid_session
      response.should redirect_to(category_participants_url)
    end
  end

end
